### ISSUE TITLE
Requesting support for CAA, HINFO, PTR, SOA, SRV, NAPTR and A6

### ISSUE THREAD

**Issue by newalphamedia** [daniesy/php-digger#1]
Hello!

First, thank you for this package that supports A, AAAA, TXT, CNAME, MX and NS. Would you please include support for CAA, HINFO, PTR, SOA, SRV, NAPTR and A6? I have tried other DNS lookup scripts but yours is the only one that seems to work for me when getting more than just the A record of a domain.

Thank you!

**Comment by daniesy** [comment]
Sure, I can implement support for these additional records. Do you happen, by any chance, to have a domain with all these records set up?

**Comment by newalphamedia** [comment]
Great! I don't actually. I'm guessing you need them to perform tests? I had a look around to find some existing domains with these records but can't find them all. I did find that Google.com has an SOA record if that helps.

I would suggest that mainly if you could add in support for SOA, SRV and CAA. PTR would be nice too for reverse DNS lookups. The HINFO is depreciated I noted and NAPTR are probably not used very often anyway? A6 records are the same as AAAA as far as I can tell, I'm not sure if anyone uses those either.

**Comment by daniesy** [comment]
I've added support for the following records `CAA`, `SRV`, `PTR` and `SOA`. I've researched `HINFO` and `A6` and they're both deprecated and shouldn't be used anymore, so I've ignored them (it's hard for me to test them either way because Cloudflare DNS lacks support for these records). 
`NAPTR` is a little more complicated to test so I'll leave this one for a future version.
